import './globals.css'
import Script from 'next/script'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script src="https://kit.fontawesome.com/eea4a3a7bd.js" crossorigin="anonymous"></Script>
      <body>{children}</body>
    </html>
  )
}
