import './globals.css'
import './phone.css'
import Link from 'next/link'
import Image from 'next/image'
import Script from 'next/script'
import map from '../public/icon_map.png'
import price from '../public/icon_user.png'
import user from '../public/icon_price.png'
import pqr from '../public/icon_pqr.png'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script src="https://kit.fontawesome.com/eea4a3a7bd.js" crossorigin="anonymous"></Script>
      <body>
        <div className="smartphone">
          <div className="content">
            {children}
            <nav>
              <Link href="/atraccion" className="nav-link">
              <Image className="nav-image"src={map}/>
                <p className="nav-item">Atraciones</p>
              </Link>
              <Link href="/usuarios"  className="nav-link">
              <Image className="nav-image"src={price}/>
                <p className="nav-item">Usuarios</p>
              </Link>
              <Link href="/premios"  className="nav-link">
                <Image className="nav-image"src={user}/>
                <p className="nav-item">Premios</p>
              </Link>
              <Link href="/PQR"  className="nav-link">  
              <Image className="nav-image"src={pqr}/>
                <p className="nav-item">PQR</p>
              </Link>
            </nav>
          </div>
        </div>
      </body>
    </html>
  )
}
